platform :ios, '7.0'
target "LZ_Demo" do
pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'MJRefresh'
pod 'CYLTabBarController'
pod 'SDWebImage', '~> 3.8.1'
pod 'Masonry', '~> 1.0.1'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.4’
end